"""
CORE PACKAGE FOR REQUESTS (automatically generated by main)

LASTEST VERSION: 1.0 alpha

STABLE VERSION: 1.0 alpha

ALL MODULES ARE INCLUDED IN THIS PACKAGE
"""

from core.version import get_version


VERSION = (1, 0, 'a')

__version__ = get_version(VERSION)

__all__ = [
    'settings',
    'request',
    'token',
    'version',
]