"""
MOODLEAPI PACKAGE FOR REQUESTS (automatically generated by main)

LASTEST VERSION: 3.0.0

STABLE VERSION: 3.0.0

ALL MODULES ARE INCLUDED IN THIS PACKAGE
"""

from moodleapi.version import get_version


VERSION = (3, 0, 0, 'f')

__version__ = get_version(VERSION)

__all__ = [
    'request',
    'security',
    'settings',
    'token',
    'version',

    'data',
]