"""
MOODLEAPI PACKAGE FOR REQUESTS (automatically generated by main)

LASTEST VERSION: 1.1

STABLE VERSION: 1.1

ALL MODULES ARE INCLUDED IN THIS PACKAGE
"""

from moodleapi.version import get_version


VERSION = (1, 1, 'a')

__version__ = get_version(VERSION)

__all__ = [
    'settings',
    'request',
    'token',
    'version',

    'data',
]